ShoppingCart.Web/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using ShoppingCart.Business.Repositories;
using ShoppingCart.DataAccess.ViewModels;
using ShoppingCart.DataAccess.Model;
using ShoppingCart.Models.Category;
using ShoppingCart.DataAccess.Constants.Enums;
using ShoppingCart.Business.Utilities;
using ShoppingCart.DataAccess.Helper;
using X.PagedList;
using System.IO;

namespace ShoppingCart.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private IUnitOfWork _unitOfWork;
        private HttpContextAccessor httpContextAccessor = new HttpContextAccessor();
        public ProductController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var user = HttpContext.Session.Get<LoggedUser>(SessionUtilities.SessionCurrentUserkey);
            return View();
        }
        [HttpGet]
        public IActionResult CreateOrUpdate(int? id)
        {
            ViewBag.Host = GetHostName();
            Product product = new Product();
            if (id == null || id == 0)
            {
                return View(product);
            }
            else
            {
                product = _unitOfWork.ProductRepository.GetT(x => x.Id == id);
                if (product == null)
                {
                    return NotFound();
                }
                else
                {
                    return View(product);
                }
            }
        }
        [HttpPost]
        public IActionResult CreateOrUpdate(Product product)
        {
            if (ModelState.IsValid)
            {
                if (product.Id == 0)
                {
                    _unitOfWork.ProductRepository.Add(product);
                }
                else
                {
                    _unitOfWork.ProductRepository.Update(product);
                }
                _unitOfWork.Save();
                int productID = product.Id;
                return Json(new { result = "OK",productID = productID });
            }
            return Json(new { result = "Fail" });
        }
        [HttpPost]
        public IActionResult Delete(int? id)
        {
            var product = _unitOfWork.ProductRepository.GetT(x => x.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            _unitOfWork.ProductRepository.Delete(product);
            _unitOfWork.Save();
            return Json(new { result = "OK" });
        }
        [HttpGet]
        public IActionResult _List(ProductListRequestModel product)
        {
            ViewBag.Host = GetHostName();
            ProductVM productVM = new ProductVM();
            if (string.IsNullOrEmpty(product.searchValue))
                productVM.Products = _unitOfWork.ProductRepository.GetAll();
            else
                productVM.Products = _unitOfWork.ProductRepository.GetAll(s => s.Name.Contains(product.searchValue));
            switch (product.sortBy)
            {
                case "Name":
                    if (product.sortDirection == "DESC")
                        productVM.Products = productVM.Products.OrderByDescending(x => x.Name);
                    else
                        productVM.Products = productVM.Products.OrderBy(x => x.Name);
                    break;
                default:
                    break;
            }
            return PartialView(productVM.Products.ToPagedList(product.Page, product.PageSize));
        }
        public string GetHostName() 
        {
            var host = HttpContext.Request.Host.ToString();
            host = Commons.GetPathImage(host);
            return host;
        }
    }
}

ShoppingCart.Web/Areas/Admin/Controllers/UploadFileController.cs
using Microsoft.AspNetCore.Mvc;
using ShoppingCart.Business.Repositories;
using ShoppingCart.DataAccess.ViewModels;
using ShoppingCart.DataAccess.Model;
using ShoppingCart.Models.Category;
using ShoppingCart.DataAccess.Constants.Enums;
using ShoppingCart.Business.Utilities;
using ShoppingCart.DataAccess.Helper;
using X.PagedList;
using System.IO;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Text.Json;
using Microsoft.CodeAnalysis;

namespace ShoppingCart.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UploadFileController : Controller
    {

        private IUnitOfWork _unitOfWork;
        private HttpContextAccessor httpContextAccessor = new HttpContextAccessor();
        public UploadFileController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public string GetHostName()
        {
            var host = HttpContext.Request.Host.ToString();
            host = Commons.GetPathImage(host);
            return host;
        }
        [HttpGet]
        public IActionResult ShowUploadFile(string isProduct, int productID)
        {
            ViewBag.Host = GetHostName();
            ViewBag.isProduct = isProduct;
            ViewBag.productID = productID;
            return PartialView("_ShowUploadFile");
        }
        [HttpGet]
        public IActionResult ShowListMedia(int mediaid)
        {
            var host = HttpContext.Request.Host.ToString();
            host = Commons.GetPathImage(host);
            var Media = _unitOfWork.UploadFileRepository.GetT(x => x.MediaID == mediaid);
            ViewBag.Media = Media;
            ViewBag.Host = host;
            return PartialView("_ShowListMedia");
        }
        [HttpPost]
        public IActionResult DeleteMedia(int mediaid, int userID, string FileName = "", int productID = 0)
        {
            var uploadfile = _unitOfWork.UploadFileRepository.GetT(x => x.MediaID == mediaid);
            if (uploadfile == null)
            {
                return NotFound();
            }
            _unitOfWork.UploadFileRepository.Delete(uploadfile);
            _unitOfWork.Save();
            // get rootFolder of image
            var folderHost = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot");
            string userFolder = $"UserID-{userID}/ProductID-{productID}";
            var folderMedia = (MediaType)1;
            var pathFolderMedia = Path.Combine("Upload", userFolder, folderMedia.ToString());
            var rootFolder = Path.Combine(folderHost, pathFolderMedia);
            try
            {
                // Check if file exists with its full path
                if (System.IO.File.Exists((Path.Combine(rootFolder, FileName))))
                {
                    // If file found, delete it
                    System.IO.File.Delete(Path.Combine(rootFolder, FileName));
                }
            }
            catch (IOException ioExp)
            {
            }
            return Json(new { result = "OK" });
        }
        [HttpPost]
        public async Task<IActionResult> AddListThumbnail(List<IFormFile> files, int userID, int productID, int MediaTypeID , int UploadTypeID)
        {
            int mediaID = 0;
            var mediaids = _unitOfWork.ProductRepository.GetT(p => p.Id == productID).MediaIds; 
            string userFolder = "";
            var folderHost = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot");
            switch (UploadTypeID)
            {
                case (int)UploadType.User:
                    userFolder = $"UserID-{userID}/Avatar";
                    
                    break;
                case (int)UploadType.Product:
                    userFolder = $"UserID-{userID}/ProductID-{productID}";
                    break;
            }
            foreach (IFormFile file in files)
            {
                if (file.Length > 0)
                {
                    var extensionFile = Path.GetExtension(file.FileName);
                    if (extensionFile == ".jpg" || extensionFile == ".png")
                    {
                        var result = await SaveThumbnail(file, folderHost, userID, userFolder, MediaTypeID, UploadTypeID,productID);
                        mediaID = result.id;
                        if(result.value == "OK")
                        {
                            mediaids = mediaids + "," + mediaID;
                        }
                        else
                        {
                            return Json(result);
                        }
                    }
                }
            }
            mediaids = mediaids.Trim(',');
            _unitOfWork.ProductRepository.UpdateMediaID(productID, mediaids);
            _unitOfWork.Save();
            return Json(new Result() {value = "OK"});
        }
        private async Task<Result> SaveThumbnail(IFormFile file, string folderHost, int userID, string userFolder, int MediaTypeID, int UploadTypeID, int productID)
        {
            var result = new Result();
            var folderMedia = (MediaType)MediaTypeID;
            var pathFolderMedia = Path.Combine("Upload", userFolder, folderMedia.ToString());
            var fullpathFolderMedia = Path.Combine(folderHost, pathFolderMedia);
            if (!Directory.Exists(fullpathFolderMedia))
            {
                Directory.CreateDirectory(fullpathFolderMedia);
            }
            var fullPathFile = Path.Combine(fullpathFolderMedia, file.FileName);
            using (var stream = new FileStream(fullPathFile, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }
            var isExist = CheckExistMedia(file.FileName, productID);
            if (!isExist)
            {
                var pathFile = Path.Combine(pathFolderMedia, file.FileName).Replace(@"\", "/");
                var uploadfile = new UploadFile
                {
                    FileName = file.FileName,
                    Thumbnail = pathFile,
                    UploadDate = DateTime.Now,
                    MediaTypeID = MediaTypeID,
                    UploadTypeID = UploadTypeID,
                    UserID = userID
                };
                _unitOfWork.UploadFileRepository.Add(uploadfile);
                _unitOfWork.Save();
                result.id = uploadfile.MediaID;
                result.value = "OK";
                result.fileName = file.FileName;
                return result;
            }
            else
            {
                result.fileName = file.FileName;
                result.value = "Fail";
                return result;
            }
        }
        public bool CheckExistMedia(string FileName, int productID)
        {
            var isExist = true;
            var mediaids = _unitOfWork.ProductRepository.GetT(x => x.Id == productID).MediaIds;

            var uploadFile = _unitOfWork.UploadFileRepository.GetListMediaByProductMediaIDs(mediaids, FileName);

            if (uploadFile.Count == 0) 
            {
                isExist = false;
            }
            return isExist;
        }
    }
}

ShoppingCart.Web/Areas/Admin/Views/UploadFile/_ShowListMedia.cshtml
@{
    var Media = ViewBag.Media;
    string host = ViewBag.Host;
    Media.Thumbnail = host + Media.Thumbnail;
}
<div  class="list-media-item m-1">
        <img src="@Media.Thumbnail"/>
        <a onclick="ProductJS.DeleteMedia(@Media.MediaID, '@Media.FileName', @Media.ProductID); return false;"><i class="fa-solid fa-xmark"></i></a>
</div>

ShoppingCart.Web/Areas/Admin/Views/UploadFile/_ShowUploadFile.cshtml
@using ShoppingCart.Business.Utilities
@using ShoppingCart.DataAccess.Constants.Enums
@using ShoppingCart.DataAccess.Model;
@using ShoppingCart.Business.Repositories
@inject IUnitOfWork _unitOfWork;
@{
    int productID = ViewBag.productID;
    var userLogged = SessionUtilities.CurrentUser(ViewContext.HttpContext.Session);
    bool isProduct = ViewBag.isProduct == "True" ? true : false;
    List<UploadFile> ListThumbnail = new List<UploadFile>();
    string mediaids = _unitOfWork.ProductRepository.GetT(p => p.Id == productID).MediaIds;
    ListThumbnail = _unitOfWork.UploadFileRepository.GetThumbnailsFromUploadFile(mediaids);
    var host = ViewBag.Host;
    
}
<form id="addMediaFileProduct" enctype="multipart/form-data" asp-controller="Product" asp-action="AddListThumbnail">
    @Html.Hidden("UserID", userLogged.UserId)
    @Html.Hidden("productID",productID)
    <div class="form-group mt-2">
        <input class="form-control" type="file" name="files" accept=".jpg,.png" id="formFile" multiple>
    </div>
    <div id="dvListMedia" class="form-group">
    @if (productID > 0)
    {
                    
        foreach(var item in ListThumbnail)
        {
            item.Thumbnail = host + item.Thumbnail;
            @Html.Hidden("UserID", item.UserID)
            <div class="list-media-item m-2" data-mediaID = "@item.MediaID">
                <img src="@item.Thumbnail"/>
                    <a onclick="ProductJS.DeleteMedia(@item.MediaID, '@item.FileName', productID); return false;"><i class="fa-solid fa-xmark"></i></a>
            </div>
        }
    }
    </div>
    <div class="form-group mt-2">
        @if (!isProduct)
        {
            <input type="button" id="btn-submitFile" data-ajax-url="@Url.Action("AddListThumbnail","UploadFile")" onclick="SubmitAddFile(@((int)(MediaType)1),@((int)(UploadType)1)); return false;" class="btn btn-primary btn-sm mt-2" value="Submit">
        }
        else
        {
            <input type="button" id="btn-submitFile" data-ajax-url="@Url.Action("AddListThumbnail","UploadFile")" onclick="ProductJS.SubmitAddFileProduct(@((int)(MediaType)1),@((int)(UploadType)2)); return false;" class="btn btn-primary btn-sm mt-2" value="Submit">
        }
        <input type="button" id="btn-Cancel" class="btn btn-secondary btn-sm mt-2" value="Cancel">
    </div>
</form>
<script type="text/javascript">
    $("#formFile").on("change", function (event) {
        for (var i = 0; i < event.target.files.length; i++) {
            var x = URL.createObjectURL(event.target.files[i]);
            $("#dvListMedia").append("<div id=''><img></div>");
            
            $("#dvListMedia div").last().attr("id", "media-" + i);
            
            $("#media-" + i).find("img").attr("src", x);
        }

    })
</script>